/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/tasks/{task}/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tasks.assignTask"];
        trace?: never;
    };
    "/users/assignable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["users.assignableUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/bulk-reassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tasks.bulkReassign"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["auth.changePassword"];
        trace?: never;
    };
    "/tasks/{task}/due-date": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tasks.changeTaskDueDate"];
        trace?: never;
    };
    "/tasks/{task}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["tasks.changeTaskStatus"];
        trace?: never;
    };
    "/comments/{comment}/attachments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["commentAttachment.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{comment}/attachments/{media}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["commentAttachment.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users.deactivateUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/departments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["department.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/my": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks.myTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notification.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/unread-count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Số chưa đọc — chuông gọi đường này, nên phải rẻ */
        get: operations["notification.show"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/read-all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Đánh dấu đã đọc tất cả */
        post: operations["notification.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/{notification}/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Đánh dấu đã đọc một thông báo */
        patch: operations["notification.update"];
        trace?: never;
    };
    "/notification-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["notificationSetting.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["notificationSetting.update"];
        trace?: never;
    };
    "/positions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["position.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["project.index"];
        put?: never;
        post: operations["project.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["project.show"];
        put?: never;
        post?: never;
        delete: operations["project.destroy"];
        options?: never;
        head?: never;
        patch: operations["project.update"];
        trace?: never;
    };
    "/projects/{project}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["projectMember.index"];
        put?: never;
        post: operations["projectMember.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project}/members/{user}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["projectMember.destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/reset-two-factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users.resetTwoFactor"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{user}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["users.resetUserPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task.index"];
        put?: never;
        post: operations["task.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["task.show"];
        put?: never;
        post?: never;
        delete: operations["task.destroy"];
        options?: never;
        head?: never;
        patch: operations["task.update"];
        trace?: never;
    };
    "/tasks/{task}/activities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["taskActivity.index"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Danh sách bình luận gốc, mới nhất ở cuối
         * @description Xếp cũ → mới, ngược với nhật ký hoạt động: người ta đọc một cuộc trao
         *     đổi theo thứ tự nó diễn ra, không đọc ngược.
         */
        get: operations["taskComment.index"];
        put?: never;
        post: operations["taskComment.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/comments/{comment}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["taskComment.destroy"];
        options?: never;
        head?: never;
        patch: operations["taskComment.update"];
        trace?: never;
    };
    "/tasks/team": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tasks.teamTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/two-factor-challenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.twoFactorChallenge"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/two-factor/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.twoFactorConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/two-factor/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth.twoFactorResend"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/two-factor/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["auth.twoFactorSetup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["user.index"];
        put?: never;
        post: operations["user.store"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ChangeDueDateRequest */
        ChangeDueDateRequest: {
            /** Format: date-time */
            due_date?: string | null;
            /**
             * @description Lý do là BẮT BUỘC. Đây là ràng buộc nghiệp vụ, không phải trường
             *     cho có: dời hạn trong im lặng làm hỏng mọi chỉ số đúng hạn.
             */
            reason: string;
        };
        /** ChangePasswordRequest */
        ChangePasswordRequest: {
            /**
             * @description `current_password` là rule sẵn có của Laravel, đối chiếu với mật
             *     khẩu của người đang đăng nhập.
             */
            current_password: string;
            password: string;
            password_confirmation: string;
        };
        /** ChangeStatusRequest */
        ChangeStatusRequest: {
            status: components["schemas"]["TaskStatus"];
        };
        /** LoginRequest */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        /** NotificationResource */
        NotificationResource: {
            /** @description Khoá chính của bảng này vốn đã là uuid, không phải số tuần tự. */
            id: string;
            kind: unknown;
            title: unknown;
            message: unknown;
            /** @description Đường dẫn tương đối trong ứng dụng, frontend tự ghép tiền tố. */
            url: unknown;
            task_id: unknown;
            actor_name: unknown;
            read_at: string | null;
            created_at: string | null;
        };
        /**
         * NotificationType
         * @description Các loại thông báo người dùng có thể bật/tắt. Đặt ở miền Identity chứ không ở Task: tuỳ chọn nhận thông báo là thuộc tính của *người dùng*, và đợt 2–4 sẽ thêm loại của báo cáo, chấm công, đơn nghỉ. Để ở Task thì miền Attendance sẽ phải gọi ngược sang Task chỉ để đọc một enum — đúng thứ quy tắc phụ thuộc cấm.  Mặc định chọn theo mức độ gấp, không bật hết mọi kênh: hộp thư đầy thông báo là hộp thư không ai đọc, và lúc đó thông báo thật sự quan trọng cũng trôi qua.
         * @enum {string}
         */
        NotificationType: "task.assigned" | "task.due_soon" | "task.overdue" | "task.comment_added" | "task.mentioned";
        /** ProjectResource */
        ProjectResource: {
            /** @description Lộ uuid, không lộ id tuần tự — xem README "Quy ước dữ liệu". */
            id: string;
            name: string;
            code: string | null;
            description: string | null;
            status: {
                value: string;
                /** @enum {string} */
                label: "Đang lên kế hoạch" | "Đang chạy" | "Tạm dừng" | "Hoàn thành" | "Đã huỷ";
                is_open: boolean;
            };
            /**
             * @description Ngày thuần, không kèm giờ: mốc dự án là ngày làm việc, không phải
             *     một thời điểm — xem README "Quy ước dữ liệu, thời gian & tiền tệ".
             */
            start_date: string | null;
            end_date: string | null;
            created_at: string | null;
            updated_at: string | null;
            owner?: {
                id: string | null;
                name: string;
                email: string;
            } | null;
            department?: {
                id: string;
                name: string;
            } | null;
            task_count?: number;
            member_count?: number;
        };
        /**
         * ProjectRole
         * @description Vai trò trong phạm vi một dự án. Khác với vai trò hệ thống (`admin`, `truong_phong`...): một trưởng phòng có thể chỉ là thành viên bình thường ở dự án của phòng khác.
         * @enum {string}
         */
        ProjectRole: "manager" | "member" | "viewer";
        /**
         * ProjectStatus
         * @enum {string}
         */
        ProjectStatus: "planning" | "active" | "on_hold" | "completed" | "cancelled";
        /**
         * Role
         * @description Vai trò trong hệ thống. Khác với `Position` (chức vụ trên giấy tờ nhân sự): vai trò quyết định làm được gì trong phần mềm. Một trưởng phòng trên danh nghĩa có thể chỉ được cấp vai trò nhân viên nếu công ty muốn vậy.  Khác với `ProjectRole` (vai trò trong phạm vi một dự án cụ thể).
         * @enum {string}
         */
        Role: "admin" | "giam_doc" | "truong_phong" | "nhan_vien";
        /** StoreAttachmentRequest */
        StoreAttachmentRequest: {
            files: string[];
        };
        /** StoreCommentRequest */
        StoreCommentRequest: {
            body: string;
            /**
             * Format: uuid
             * @description Nhận uuid chứ không nhận id tuần tự. Bình luận cha phải thuộc
             *     đúng task này — kiểm ở controller vì cần biết task nào.
             */
            parent_id?: string | null;
        };
        /** StoreProjectMemberRequest */
        StoreProjectMemberRequest: {
            /** Format: uuid */
            user_id: string;
            role?: components["schemas"]["ProjectRole"] | null;
        };
        /** StoreProjectRequest */
        StoreProjectRequest: {
            name: string;
            /**
             * @description Mã dự án là thứ mọi người gõ trong báo cáo và tên nhánh git, nên
             *     phải duy nhất kể cả với dự án đã xoá mềm — trùng mã là tra cứu
             *     sau này ra hai kết quả khác nhau.
             */
            code?: string | null;
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"] | null;
            /** Format: date-time */
            start_date?: string | null;
            /** Format: date-time */
            end_date?: string | null;
            /**
             * Format: uuid
             * @description Nhận uuid chứ không nhận id tuần tự.
             */
            owner_id?: string | null;
            /** Format: uuid */
            department_id?: string | null;
        };
        /** StoreTaskRequest */
        StoreTaskRequest: {
            title: string;
            description?: string | null;
            priority?: components["schemas"]["TaskPriority"] | null;
            /** Format: date-time */
            due_date?: string | null;
            /** @description DECIMAL(6,2) — xem README "Quy ước dữ liệu, thời gian & tiền tệ". */
            estimate_hours?: number | null;
            /**
             * Format: uuid
             * @description Nhận uuid chứ không nhận id tuần tự. Chỉ nhận dự án còn mở: dự án đã hoàn thành hoặc đã huỷ mà vẫn
             *     nhận việc mới thì mọi báo cáo tiến độ dự án đều sai.
             */
            project_id?: string | null;
            /** Format: uuid */
            parent_task_id?: string | null;
            /** Format: uuid */
            assignee_id?: string | null;
            /** Format: uuid */
            reviewer_id?: string | null;
        };
        /** StoreUserRequest */
        StoreUserRequest: {
            name: string;
            /** Format: email */
            email: string;
            employee_code: string;
            role: components["schemas"]["Role"];
            phone?: string | null;
            /** Format: date-time */
            joined_at?: string | null;
            /**
             * Format: uuid
             * @description Nhận uuid chứ không nhận id tuần tự — xem README "Quy ước dữ liệu".
             */
            department_id?: string | null;
            /** Format: uuid */
            position_id?: string | null;
            /** Format: uuid */
            manager_id?: string | null;
        };
        /** Stringable */
        Stringable: string;
        /** TaskActivityResource */
        TaskActivityResource: {
            id: number;
            event: string;
            old_values: unknown[] | null;
            new_values: unknown[] | null;
            created_at: string | null;
            causer?: {
                id: string | null;
                name: string;
            } | null;
        };
        /** TaskCommentResource */
        TaskCommentResource: {
            id: string;
            /**
             * @description Nội dung giữ nguyên dạng thô kèm dấu nhắc `@[Tên](uuid)`.
             *     Frontend tự dựng thành chip — server không sinh HTML, để không
             *     có đường nào biến nội dung người dùng thành thẻ chạy được.
             */
            body: string;
            created_at: string | null;
            edited_at: string | null;
            parent_id?: string | null;
            author?: {
                id: string | null;
                name: string;
                email: string;
            } | null;
            mentions?: string[];
            attachments?: string[];
            reply_count?: number;
        };
        /**
         * TaskPriority
         * @enum {string}
         */
        TaskPriority: "low" | "normal" | "high" | "urgent";
        /** TaskResource */
        TaskResource: {
            /** @description Lộ uuid, không lộ id tuần tự — xem README "Quy ước dữ liệu". */
            id: string;
            title: string;
            description: string | null;
            status: {
                value: string;
                /** @enum {string} */
                label: "Chưa bắt đầu" | "Đang làm" | "Chờ duyệt" | "Hoàn thành" | "Tạm dừng" | "Đã huỷ";
                is_closed: boolean;
            };
            priority: {
                value: string;
                /** @enum {string} */
                label: "Thấp" | "Bình thường" | "Cao" | "Khẩn cấp";
            };
            /**
             * @description ISO 8601 kèm offset — frontend tự đổi sang giờ Việt Nam.
             *     Xem README "Quy ước dữ liệu, thời gian & tiền tệ".
             */
            due_date: string | null;
            started_at: string | null;
            completed_at: string | null;
            created_at: string | null;
            updated_at: string | null;
            estimate_hours: string | null;
            progress_percent: number;
            /** @description Hiển thị công khai để việc dời hạn không diễn ra trong im lặng. */
            due_date_change_count: number;
            is_overdue: string;
            project?: {
                id: string;
                name: string;
            } | null;
            assignee?: {
                id: string;
                name: string;
                email: string;
            } | null;
            assigner?: {
                id: string;
                name: string;
                email: string;
            } | null;
            reviewer?: {
                id: string;
                name: string;
                email: string;
            } | null;
            labels?: string[];
            subtask_count?: number;
            comment_count?: number;
        };
        /**
         * TaskStatus
         * @description Trạng thái của một task. Giá trị lưu dưới dạng chuỗi để đọc dump database vẫn hiểu được, và thêm trạng thái mới không phải migrate — xem README, "Quy ước dữ liệu".
         * @enum {string}
         */
        TaskStatus: "todo" | "in_progress" | "review" | "done" | "on_hold" | "cancelled";
        /** TwoFactorChallengeRequest */
        TwoFactorChallengeRequest: {
            /** @description Một trong hai: mã 6 số từ ứng dụng, hoặc mã khôi phục. */
            code?: string | null;
            recovery_code?: string | null;
        };
        /**
         * UpdateProjectRequest
         * @description PATCH sửa từng phần: chỉ kiểm tra những trường thực sự gửi lên.
         *
         *     Dùng `sometimes` thay vì `required` — nếu không, sửa mỗi mô tả cũng bắt gửi
         *     kèm tên dự án, và client nào quên là ghi đè mất dữ liệu.
         */
        UpdateProjectRequest: {
            name?: string;
            code?: string | null;
            description?: string | null;
            status?: components["schemas"]["ProjectStatus"];
            /** Format: date-time */
            start_date?: string | null;
            /** Format: date-time */
            end_date?: string | null;
            /** Format: uuid */
            owner_id?: string | null;
            /** Format: uuid */
            department_id?: string | null;
        };
        /** UserResource */
        UserResource: {
            /** @description Lộ uuid, không lộ id tuần tự — xem README "Quy ước dữ liệu". */
            id: string | null;
            name: string;
            email: string;
            employee_code: string | null;
            phone: string | null;
            is_active: boolean;
            joined_at: string | null;
            department?: {
                id: string;
                name: string;
                code: string | null;
            } | null;
            position?: {
                id: string;
                name: string;
                level: number;
            } | null;
            roles: string[];
            permissions: unknown[];
        };
    };
    responses: {
        /** @description Validation error */
        ValidationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Errors overview. */
                    message: string;
                    /** @description A detailed description of each field that failed validation. */
                    errors: {
                        [key: string]: string[];
                    };
                };
            };
        };
        /** @description Unauthenticated */
        AuthenticationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Authorization error */
        AuthorizationException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
        /** @description Not found */
        ModelNotFoundException: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @description Error overview. */
                    message: string;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "tasks.assignTask": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    assignee_id?: string | null;
                };
            };
        };
        responses: {
            /** @description `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "users.assignableUsers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tasks.bulkReassign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    from_user_id: string;
                    /** Format: uuid */
                    to_user_id: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            reassigned: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.changePassword": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "tasks.changeTaskDueDate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeDueDateRequest"];
            };
        };
        responses: {
            /** @description `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "tasks.changeTaskStatus": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeStatusRequest"];
            };
        };
        responses: {
            /** @description `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "commentAttachment.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The comment UUID */
                comment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["StoreAttachmentRequest"];
            };
        };
        responses: {
            /** @description `TaskCommentResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskCommentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "commentAttachment.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The comment UUID */
                comment: string;
                media: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.deactivateUser": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user UUID */
                user: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "department.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /**
             * @description Chưa bật: buộc thiết lập. Mã sẽ gửi khi họ gọi /two-factor/setup,
             *     không gửi ở đây — tránh gửi thừa nếu họ bỏ dở ngay.
             */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            two_factor_required: boolean;
                            channel: string;
                            can_resend: boolean;
                            sent_to: string | null;
                        };
                    } | {
                        data: {
                            two_factor_setup_required: boolean;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error overview. */
                        message: string;
                    };
                };
            };
        };
    };
    "auth.logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "auth.me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "tasks.myTasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            overdue: unknown[];
                            today: unknown[];
                            this_week: unknown[];
                            /** @description Việc chưa có hạn xếp chung với việc xa — chúng không gấp. */
                            later: unknown[];
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "notification.index": {
        parameters: {
            query?: {
                unread?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `NotificationResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["NotificationResource"][];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "notification.show": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            unread: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "notification.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            marked: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "notification.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                notification: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            read: boolean;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "notificationSetting.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: unknown[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "notificationSetting.update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type: components["schemas"]["NotificationType"];
                    in_app: boolean;
                    email: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: unknown[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "position.index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string[];
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
        };
    };
    "project.index": {
        parameters: {
            query?: {
                status?: string;
                open?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `ProjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["ProjectResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "project.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreProjectRequest"];
            };
        };
        responses: {
            /** @description `ProjectResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "project.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project UUID */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `ProjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "project.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project UUID */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "project.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project UUID */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description `ProjectResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["ProjectResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "projectMember.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project UUID */
                project: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: string;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "projectMember.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project UUID */
                project: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreProjectMemberRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            user_id: components["schemas"]["Stringable"];
                            role: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "projectMember.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The project UUID */
                project: string;
                /** @description The user UUID */
                user: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.resetTwoFactor": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user UUID */
                user: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "users.resetUserPassword": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The user UUID */
                user: string | null;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Hiện đúng một lần. Không lưu lại, không gửi email. */
                            temporary_password: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "task.index": {
        parameters: {
            query?: {
                status?: string;
                priority?: string;
                assignee_id?: string;
                project_id?: string;
                overdue?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["TaskResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "task.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreTaskRequest"];
            };
        };
        responses: {
            /** @description `TaskResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "task.show": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "task.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "task.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreTaskRequest"];
            };
        };
        responses: {
            /** @description `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "taskActivity.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TaskActivityResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["TaskActivityResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "taskComment.index": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TaskCommentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["TaskCommentResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "taskComment.store": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The task UUID */
                task: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCommentRequest"];
            };
        };
        responses: {
            /** @description `TaskCommentResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskCommentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "taskComment.destroy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The comment UUID */
                comment: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
        };
    };
    "taskComment.update": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The comment UUID */
                comment: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreCommentRequest"];
            };
        };
        responses: {
            /** @description `TaskCommentResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["TaskCommentResource"] & Record<string, never>;
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            404: components["responses"]["ModelNotFoundException"];
            422: components["responses"]["ValidationException"];
        };
    };
    "tasks.teamTasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `TaskResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["TaskResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            /** @description An error */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /**
                         * @description Error overview.
                         * @example
                         */
                        message: string;
                    };
                };
            };
        };
    };
    "auth.twoFactorChallenge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TwoFactorChallengeRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"] & Record<string, never>;
                    };
                };
            };
            422: components["responses"]["ValidationException"];
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error overview. */
                        message: string;
                    };
                };
            };
        };
    };
    "auth.twoFactorConfirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["TwoFactorChallengeRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            /** @description Hiện đúng một lần. Người dùng phải lưu lại ngay. */
                            recovery_codes: unknown[] | null;
                        };
                    };
                };
            };
            422: components["responses"]["ValidationException"];
        };
    };
    "auth.twoFactorResend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            sent_to: string;
                            can_resend: boolean;
                        };
                    };
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Error overview. */
                        message: string;
                    };
                };
            };
        };
    };
    "auth.twoFactorSetup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: {
                            channel: string;
                            instructions: string;
                            secret: string | null;
                            qr_code_svg: string | null;
                            sent_to: string | null;
                            can_resend: boolean;
                        };
                    };
                };
            };
        };
    };
    "user.index": {
        parameters: {
            query?: {
                department_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated set of `UserResource` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: (components["schemas"]["UserResource"] & Record<string, never>)[];
                        links: {
                            first: string | null;
                            last: string | null;
                            prev: string | null;
                            next: string | null;
                        };
                        meta: {
                            current_page: number;
                            from: number | null;
                            last_page: number;
                            /** @description Generated paginator links. */
                            links: {
                                url: string | null;
                                label: string;
                                active: boolean;
                            }[];
                            /** @description Base path for paginator generated URLs. */
                            path: string | null;
                            /** @description Number of items shown per page. */
                            per_page: number;
                            /** @description Number of the last item in the slice. */
                            to: number | null;
                            /** @description Total number of items being paginated. */
                            total: number;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
        };
    };
    "user.store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StoreUserRequest"];
            };
        };
        responses: {
            /** @description `UserResource` */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["UserResource"] & Record<string, never>;
                        meta: {
                            temporary_password: string;
                        };
                    };
                };
            };
            401: components["responses"]["AuthenticationException"];
            403: components["responses"]["AuthorizationException"];
            422: components["responses"]["ValidationException"];
        };
    };
}
